version: '3.8'

services:
  # db:
  #   image: postgres:latest
  #   container_name: master-chef-db
  #   environment:
  #     POSTGRES_DB: db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network

  app:
    build: .
    container_name: master-chef-app
    ports:
      - "8080:8080"
    environment:
      TOKEN: ${TOKEN}
      URL: ${URL}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    # depends_on:
    #   - db
    networks:
      - master-chef-network

networks:
  master-chef-network:
    external: true

# networks:
#   app-network: